name: linear_programming_with_or_tools
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.2
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=20.3.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - bleach=3.3.0
  - ca-certificates=2020.12.5
  - certifi=2020.12.5
  - cffi=1.14.4
  - dbus=1.13.18
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.10
  - gettext=0.19.8.1
  - glib=2.66.6
  - glib-tools=2.66.6
  - icu=64.2
  - importlib-metadata=3.4.0
  - importlib_metadata=3.4.0
  - ipykernel=5.1.0
  - ipython=7.20.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - jedi=0.18.0
  - jinja2=2.11.3
  - jpeg=9d
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.11
  - jupyter_console=6.2.0
  - jupyter_core=4.7.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=11.0.1
  - libffi=3.3
  - libgfortran=5.0.0
  - libgfortran5=9.3.0
  - libglib=2.66.6
  - libiconv=1.16
  - liblapack=3.9.0
  - libopenblas=0.3.12
  - libpng=1.6.37
  - libsodium=1.0.18
  - llvm-openmp=11.0.1
  - markupsafe=1.1.1
  - mistune=0.8.4
  - nbclient=0.5.2
  - nbconvert=6.0.7
  - nbformat=5.1.2
  - ncurses=6.2
  - nest-asyncio=1.4.3
  - notebook=6.2.0
  - numpy=1.20.1
  - openssl=1.1.1i
  - packaging=20.9
  - pandas=1.2.2
  - pandoc=2.11.4
  - pandocfilters=1.4.2
  - parso=0.8.1
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=21.0.1
  - plotly=4.14.3
  - prometheus_client=0.9.0
  - prompt-toolkit=3.0.14
  - prompt_toolkit=3.0.14
  - ptyprocess=0.7.0
  - pycparser=2.20
  - pygments=2.7.4
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - python=3.8.6
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2021.1
  - pyzmq=22.0.1
  - qt=5.9.7
  - qtconsole=5.0.2
  - qtpy=1.9.0
  - readline=8.0
  - retrying=1.3.3
  - send2trash=1.5.0
  - setuptools=49.6.0
  - sip=4.19.8
  - six=1.15.0
  - sqlite=3.34.0
  - terminado=0.9.2
  - testpath=0.4.4
  - tk=8.6.10
  - tornado=6.1
  - traitlets=5.0.5
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - widgetsnbextension=3.5.1
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.4.0
  - zlib=1.2.11
  - pip:
    - absl-py==0.11.0
    - ortools==8.1.8487
    - protobuf==3.14.0
